image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5013
    onOpen: ignore
  - port: 3000

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: git clone https://github.com/LukasBoll/glsp-examples.git &&
    cd glsp-examples/minimal/server/org.eclipse.glsp.example.minimal && mvn clean install &&
    cd ../../client && yarn && cd ../../.. &&
    cp -r .tutorial/test/ ./glsp-examples/minimal/server/org.eclipse.glsp.example.minimal/src/ && cp .tutorial/pom.xml ./glsp-examples/minimal/server/org.eclipse.glsp.example.minimal/

vscode:
  extensions:
    - minrows.educode

github:
  prebuilds:
    master: true
